management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  server:
    port: 8080
  metrics:
    tags:
      application: nolzo-app
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 500ms, 1500ms
